/**
 * GENERATED by scripts/landing-panel-data.ts. Do not edit by hand.
 *
 * Real product output for the landing page's Capabilities panels: every
 * figure below was computed by the shipped engines against live provider
 * data at the timestamp in `meta`. Regenerate with:
 *
 *   npx tsx scripts/landing-panel-data.ts
 */
export const PANEL_DATA = {
  "meta": {
    "generatedAt": "2026-08-10T20:58:25.133Z",
    "gitSha": "97bf6f4",
    "appVersion": "0.1.0",
    "generator": "scripts/landing-panel-data.ts"
  },
  "valuation": {
    "symbol": "V",
    "name": "Visa Inc.",
    "currency": "USD",
    "spot": 361.32,
    "spotDisplay": "$361.32",
    "asOf": "2026-08-10",
    "method": "Discounted free cash flow",
    "unit": "US$B",
    "assumptions": [
      {
        "key": "baseFcf",
        "label": "Trailing FCF",
        "display": "$20.4B",
        "source": "Yahoo",
        "rationale": "Trailing twelve-month free cash flow."
      },
      {
        "key": "growthRate1",
        "label": "FCF growth Y1–5",
        "display": "6.5%",
        "source": "History",
        "rationale": "Seeded from what the business delivered: FCF CAGR FY2022→FY2025."
      },
      {
        "key": "growthRate2",
        "label": "FCF growth Y6–10",
        "display": "3.2%",
        "source": "History",
        "rationale": "Faded to half the stage-one rate by year ten."
      },
      {
        "key": "terminalGrowth",
        "label": "Terminal growth",
        "display": "2.5%",
        "source": "Default",
        "rationale": "Long-run perpetuity growth."
      },
      {
        "key": "discountRate",
        "label": "WACC",
        "display": "6.7%",
        "source": "CAPM",
        "rationale": "CAPM: levered beta, region risk-free rate and ERP, after-tax cost of debt."
      },
      {
        "key": "sharesOutstanding",
        "label": "Shares outstanding",
        "display": "1.70B",
        "source": "Yahoo",
        "rationale": "Shares outstanding as reported."
      },
      {
        "key": "netDebt",
        "label": "Net debt",
        "display": "$10.1B",
        "source": "Yahoo",
        "rationale": "Total debt less cash and equivalents."
      }
    ],
    "actuals": [
      {
        "year": "FY22",
        "value": 17879000000,
        "kind": "actual"
      },
      {
        "year": "FY23",
        "value": 19696000000,
        "kind": "actual"
      },
      {
        "year": "FY24",
        "value": 18693000000,
        "kind": "actual"
      },
      {
        "year": "FY25",
        "value": 21577000000,
        "kind": "actual"
      }
    ],
    "scenarios": [
      {
        "id": "bear",
        "label": "Bear",
        "delta": "Growth -3.2pp, WACC +2.0pp → 3.2%/1.2% @ 8.7%",
        "fairValue": "$195.67",
        "upside": "-45.8%",
        "upsidePositive": false,
        "forecast": [
          {
            "year": "FY26E",
            "value": 21063787365.50818,
            "kind": "forecast"
          },
          {
            "year": "FY27E",
            "value": 21744908913.90178,
            "kind": "forecast"
          },
          {
            "year": "FY28E",
            "value": 22448055303.110367,
            "kind": "forecast"
          },
          {
            "year": "FY29E",
            "value": 23173938731.439915,
            "kind": "forecast"
          },
          {
            "year": "FY30E",
            "value": 23923294426.93955,
            "kind": "forecast"
          },
          {
            "year": "FY31E",
            "value": 24601188214.386765,
            "kind": "forecast"
          },
          {
            "year": "FY32E",
            "value": 25199886141.316196,
            "kind": "forecast"
          },
          {
            "year": "FY33E",
            "value": 25712354519.429592,
            "kind": "forecast"
          },
          {
            "year": "FY34E",
            "value": 26132395107.44777,
            "kind": "forecast"
          },
          {
            "year": "FY35E",
            "value": 26454767956.313637,
            "kind": "forecast"
          }
        ],
        "bridge": {
          "pvExplicit": "$153.6B",
          "pvTerminal": "$189.9B",
          "netDebt": "$10.1B",
          "equityValue": "$333.4B",
          "shares": "1.70B",
          "perShare": "$195.67"
        }
      },
      {
        "id": "base",
        "label": "Base",
        "delta": null,
        "fairValue": "$370.69",
        "upside": "+2.6%",
        "upsidePositive": true,
        "forecast": [
          {
            "year": "FY26E",
            "value": 21723573963.016357,
            "kind": "forecast"
          },
          {
            "year": "FY27E",
            "value": 23128486961.57441,
            "kind": "forecast"
          },
          {
            "year": "FY28E",
            "value": 24624258883.110683,
            "kind": "forecast"
          },
          {
            "year": "FY29E",
            "value": 26216765781.08417,
            "kind": "forecast"
          },
          {
            "year": "FY30E",
            "value": 27912263726.7124,
            "kind": "forecast"
          },
          {
            "year": "FY31E",
            "value": 29536898419.697987,
            "kind": "forecast"
          },
          {
            "year": "FY32E",
            "value": 31065073207.053673,
            "kind": "forecast"
          },
          {
            "year": "FY33E",
            "value": 32471407526.4817,
            "kind": "forecast"
          },
          {
            "year": "FY34E",
            "value": 33731407448.955658,
            "kind": "forecast"
          },
          {
            "year": "FY35E",
            "value": 34822150916.5217,
            "kind": "forecast"
          }
        ],
        "bridge": {
          "pvExplicit": "$197.5B",
          "pvTerminal": "$444.3B",
          "netDebt": "$10.1B",
          "equityValue": "$631.7B",
          "shares": "1.70B",
          "perShare": "$370.69"
        }
      },
      {
        "id": "bull",
        "label": "Bull",
        "delta": "Growth +3.2pp, WACC -1.0pp → 9.7%/5.2% @ 5.7%",
        "fairValue": "$628.40",
        "upside": "+73.9%",
        "upsidePositive": true,
        "forecast": [
          {
            "year": "FY26E",
            "value": 22383360560.52454,
            "kind": "forecast"
          },
          {
            "year": "FY27E",
            "value": 24554734911.01789,
            "kind": "forecast"
          },
          {
            "year": "FY28E",
            "value": 26936750847.57833,
            "kind": "forecast"
          },
          {
            "year": "FY29E",
            "value": 29549842376.792877,
            "kind": "forecast"
          },
          {
            "year": "FY30E",
            "value": 32416425775.85804,
            "kind": "forecast"
          },
          {
            "year": "FY31E",
            "value": 35271468777.46117,
            "kind": "forecast"
          },
          {
            "year": "FY32E",
            "value": 38062835356.895325,
            "kind": "forecast"
          },
          {
            "year": "FY33E",
            "value": 40735038598.75732,
            "kind": "forecast"
          },
          {
            "year": "FY34E",
            "value": 43230898613.845055,
            "kind": "forecast"
          },
          {
            "year": "FY35E",
            "value": 45493436916.94175,
            "kind": "forecast"
          }
        ],
        "bridge": {
          "pvExplicit": "$243.8B",
          "pvTerminal": "$837.1B",
          "netDebt": "$10.1B",
          "equityValue": "$1070.9B",
          "shares": "1.70B",
          "perShare": "$628.40"
        }
      }
    ],
    "terminalValueShare": "69%",
    "pricedInGrowth": {
      "label": "Priced-in growth",
      "display": "6.1%"
    },
    "deliveredGrowth": {
      "label": "FCF CAGR FY2022→FY2025",
      "display": "6.5%"
    }
  },
  "research": {
    "symbol": "AAPL",
    "name": "Apple Inc.",
    "exchange": "NASDAQ",
    "industry": "Consumer Electronics",
    "price": "$308.26",
    "changePercent": "-1.53%",
    "changePositive": false,
    "asOf": "2026-08-10",
    "asOfShort": "Aug 10",
    "tabs": [
      "Conviction",
      "Analysis",
      "Financials",
      "Ownership",
      "Details"
    ],
    "metrics": [
      [
        "Market cap",
        "$4.50T"
      ],
      [
        "Enterprise value",
        "$4.59T"
      ],
      [
        "Revenue (TTM)",
        "$466.8B"
      ],
      [
        "Net income (TTM)",
        "$128.9B"
      ],
      [
        "P/E (TTM)",
        "35.4x"
      ],
      [
        "Dividend yield",
        "0.34%"
      ]
    ],
    "revenue": [
      {
        "year": "FY22",
        "value": 394328000000
      },
      {
        "year": "FY23",
        "value": 383285000000
      },
      {
        "year": "FY24",
        "value": 391035000000
      },
      {
        "year": "FY25",
        "value": 416161000000
      },
      {
        "year": "TTM",
        "value": 466822987776
      }
    ],
    "revenueTtmDisplay": "$466.8B",
    "revenueGrowthDisplay": "+16.4% YoY",
    "revenueGrowthPositive": true,
    "news": [
      {
        "headline": "Apple downgraded at Jefferies over iPhone yields and growth concerns",
        "date": "Aug 10"
      },
      {
        "headline": "Apple (AAPL) Downgraded as Soaring Memory Costs Test iPhone Pricing Power",
        "date": "Aug 10"
      },
      {
        "headline": "One quiet Apple update could matter more than it looks",
        "date": "Aug 10"
      }
    ]
  },
  "screener": {
    "filters": [
      "Market cap > $1B",
      "Forward P/E < 25",
      "Revenue growth > 10%",
      "ROIC > 12%"
    ],
    "total": 145,
    "universe": 1556,
    "screenedIn": "0.01s",
    "builtAt": "2026-08-10T20:58:20.311Z",
    "rows": [
      {
        "ticker": "SKHY",
        "company": "SK hynix Inc.",
        "cap": "$960.4B",
        "pe": "4.3x",
        "growth": "256.8%",
        "roic": "28.1%",
        "score": 99,
        "confidence": 100
      },
      {
        "ticker": "KGC",
        "company": "Kinross Gold Corporation",
        "cap": "$32.5B",
        "pe": "9.2x",
        "growth": "29.5%",
        "roic": "26.8%",
        "score": 98,
        "confidence": 100
      },
      {
        "ticker": "AU",
        "company": "AngloGold Ashanti plc",
        "cap": "$49.2B",
        "pe": "9.7x",
        "growth": "27.0%",
        "roic": "31.2%",
        "score": 97,
        "confidence": 100
      },
      {
        "ticker": "IAG",
        "company": "IAMGOLD Corporation",
        "cap": "$10.5B",
        "pe": "8.0x",
        "growth": "47.5%",
        "roic": "17.3%",
        "score": 97,
        "confidence": 100
      },
      {
        "ticker": "BCRX",
        "company": "BioCryst Pharmaceuticals, Inc.",
        "cap": "$2.5B",
        "pe": "10.5x",
        "growth": "33.6%",
        "roic": "109.6%",
        "score": 97,
        "confidence": 100
      },
      {
        "ticker": "TSM",
        "company": "Taiwan Semiconductor Manufacturing Company Limited",
        "cap": "$2.17T",
        "pe": "19.4x",
        "growth": "36.0%",
        "roic": "25.2%",
        "score": 96,
        "confidence": 100
      },
      {
        "ticker": "BTG",
        "company": "B2Gold Corp.",
        "cap": "$6.7B",
        "pe": "4.6x",
        "growth": "117.7%",
        "roic": "28.5%",
        "score": 96,
        "confidence": 100
      },
      {
        "ticker": "FSM",
        "company": "Fortuna Mining Corp.",
        "cap": "$3.2B",
        "pe": "6.1x",
        "growth": "38.2%",
        "roic": "14.7%",
        "score": 96,
        "confidence": 100
      }
    ]
  },
  "portfolio": {
    "valueDisplay": "$3,488,398",
    "totalReturnDisplay": "+2.3%",
    "totalReturnPositive": true,
    "sinceLabel": "May 2026",
    "health": "75",
    "healthGrade": "B",
    "volatilityDisplay": "8.3%",
    "trajectory": [
      {
        "at": "2026-05-04",
        "value": 850000
      },
      {
        "at": "2026-05-05",
        "value": 850001.683139038
      },
      {
        "at": "2026-05-06",
        "value": 853149.320791626
      },
      {
        "at": "2026-05-07",
        "value": 853554.3651214599
      },
      {
        "at": "2026-05-08",
        "value": 858985.5695892334
      },
      {
        "at": "2026-05-12",
        "value": 858382.7430450439
      },
      {
        "at": "2026-05-15",
        "value": 856731.4183685302
      },
      {
        "at": "2026-05-19",
        "value": 851219.3302947998
      },
      {
        "at": "2026-06-16",
        "value": 869540.9967834472
      },
      {
        "at": "2026-06-18",
        "value": 865469.5861114502
      },
      {
        "at": "2026-06-22",
        "value": 1110997.8760589599
      },
      {
        "at": "2026-06-23",
        "value": 1104073.3606951905
      },
      {
        "at": "2026-06-25",
        "value": 1102252.2730059815
      },
      {
        "at": "2026-07-01",
        "value": 1139167.7723101806
      },
      {
        "at": "2026-07-07",
        "value": 1147682.1740618898
      },
      {
        "at": "2026-07-21",
        "value": 1145038.5727404784
      },
      {
        "at": "2026-07-22",
        "value": 1136480.2287554932
      },
      {
        "at": "2026-07-24",
        "value": 1127050.0072222902
      },
      {
        "at": "2026-08-03",
        "value": 1180398.331746216
      },
      {
        "at": "2026-08-06",
        "value": 3194831.519999462
      },
      {
        "at": "2026-08-06",
        "value": 3488397.5199995763
      }
    ],
    "allocation": [
      {
        "label": "Equities",
        "pct": "35.8%",
        "weight": 35.77234870029153
      },
      {
        "label": "Bonds",
        "pct": "25.0%",
        "weight": 25.000000000000522
      },
      {
        "label": "ETFs",
        "pct": "19.2%",
        "weight": 19.207838305364803
      },
      {
        "label": "Cash",
        "pct": "13.0%",
        "weight": 13.019812994344468
      },
      {
        "label": "REITs",
        "pct": "7.0%",
        "weight": 6.999999999998686
      }
    ],
    "findings": [
      "Health 75 (B), volatility 8.3%",
      "Equities is the largest sleeve at 35.8%",
      "5 asset classes held; top weight 35.8%"
    ],
    "movers": [
      {
        "ticker": "XOM",
        "delta": "+4.41%",
        "up": true
      },
      {
        "ticker": "LLY",
        "delta": "+3.90%",
        "up": true
      },
      {
        "ticker": "ABNB",
        "delta": "+3.72%",
        "up": true
      },
      {
        "ticker": "COIN",
        "delta": "-3.20%",
        "up": false
      },
      {
        "ticker": "DASH",
        "delta": "-2.96%",
        "up": false
      }
    ],
    "moversAsOf": "2026-08-10"
  },
  "assistant": {
    "question": "Why is fair value $370.69 when Visa Inc. trades at $361.32?",
    "answer": "The engine discounts trailing FCF $20.4B at a WACC 6.7% from CAPM, growing 6.5% in Y1-5 (the delivered FCF CAGR FY2022→FY2025) then fading to 3.2%, with terminal growth 2.5%. That bridge, PV explicit $197.5B + PV terminal $444.3B - net debt $10.1B = equity $631.7B over 1.70B shares, gives $370.69, or +2.6% vs spot. The gap is small because the market is priced-in growth of 6.1%, just under the delivered 6.5%.",
    "model": "claude-opus-5-medium",
    "generatedAt": "2026-08-10",
    "context": {
      "symbol": "V",
      "name": "Visa Inc.",
      "fairValue": "$370.69",
      "upside": "+2.6%",
      "upsidePositive": true,
      "spot": "$361.32"
    },
    "sources": [
      "Valuation case V",
      "Reverse DCF",
      "Data: Yahoo, 2026-08-10"
    ]
  }
} as const;

export type PanelData = typeof PANEL_DATA;
