"use client";

import { useState } from "react";
import { ArrowUpRight, ArrowDownRight } from "lucide-react";
import { useMockupEntry } from "../motion/mockup";
import { Odometer } from "../primitives/odometer";
import { PANEL_DATA } from "./panel-data";

/**
 * Valuation Engine panel: REAL output of the shipped two-stage DCF
 * (lib/valuation/dcf.ts) for the ticker in panel-data.ts, generated by
 * scripts/landing-panel-data.ts. Nothing here is authored by hand: the
 * assumptions, their sources, the projection bars, the scenario deltas and
 * the fair value are all engine output, reproducible on demand.
 *
 * The composition argues the product's thesis:
 *   - left rail: the full assumption set, each input with its provenance
 *   - chart: labelled free cash flow, actuals split from forecast
 *   - bridge: the arithmetic from cash flows to per-share value
 *   - scenario tabs: bear/base/bull are the same engine under shifted
 *     inputs, so switching them demonstrates that changing an input
 *     changes the output
 *
 * Choreographed ONCE on first viewport entry: assumption rows check in
 * staggered, actual bars grow first, forecast bars follow after a gap, the
 * fair value rolls digit by digit. Scenario switch morphs bar heights and
 * rolls the value. No-JS / reduced motion: the base case renders settled.
 */
const V = PANEL_DATA.valuation;
const SCENARIOS = V.scenarios;
const BASE_INDEX = SCENARIOS.findIndex((s) => s.id === "base");

/** Y scale shared across scenarios so a morph reads as the forecast changing. */
const MAX_VALUE = Math.max(
  ...V.actuals.map((b) => b.value),
  ...SCENARIOS.flatMap((s) => s.forecast.map((b) => b.value)),
);
const NICE_MAX = Math.ceil(MAX_VALUE / 1e9 / 10) * 10 * 1e9;

export function ValuationPanel() {
  const { ref, phase, played } = useMockupEntry();
  const [scen, setScen] = useState(BASE_INDEX);
  const s = SCENARIOS[scen];
  const bars = [...V.actuals, ...s.forecast];

  return (
    // Mobile collapse: value + labelled chart stack ABOVE the assumption
    // rail (column-reverse), because the assumptions are the argument and
    // must survive full-width rather than being cropped away.
    <div ref={ref} data-mock={phase} className="flex h-full flex-col-reverse gap-2.5 p-4 text-left sm:flex-row">
      {/* Assumptions rail: the argument. Every input, sourced. */}
      <div className="flex w-full flex-col rounded-card border border-hairline bg-surface-2/60 p-2.5 sm:w-44 sm:shrink-0">
        <p className="px-1.5 text-caption font-semibold text-foreground">Assumptions</p>
        <p className="px-1.5 pt-0.5 text-micro text-muted">Every input sourced. Edit one and the value moves.</p>
        <ul className="mt-1.5 flex flex-1 flex-col justify-evenly gap-1 px-1.5">
          {V.assumptions.map((a, i) => (
            <li
              key={a.key}
              style={{ transitionDelay: `${200 + i * 70}ms` }}
              className="flex items-baseline justify-between gap-2 transition-[opacity,transform] duration-500 ease-out [[data-mock=armed]_&]:translate-y-2 [[data-mock=armed]_&]:opacity-0"
              title={a.rationale}
            >
              <span className="text-micro leading-tight text-muted">{a.label}</span>
              <span className="text-right">
                <span className="block font-mono text-caption font-medium leading-tight tabular-nums text-foreground">
                  {a.display}
                </span>
                <span className="block text-micro leading-tight text-brand">{a.source}</span>
              </span>
            </li>
          ))}
        </ul>
        <p className="mt-1.5 border-t border-hairline px-1.5 pt-1.5 text-micro leading-snug text-muted">
          Terminal value carries {V.terminalValueShare} of base-case EV.
        </p>
      </div>

      {/* Main area: value, labelled chart, derivation. */}
      <div className="flex min-w-0 flex-1 flex-col rounded-card border border-hairline bg-surface-2/60 p-3.5">
        <div className="flex flex-wrap items-start justify-between gap-x-3 gap-y-1.5">
          <div>
            <p className="text-caption font-semibold text-foreground">
              {V.name} <span className="font-normal text-muted">{V.symbol}</span>
            </p>
            <p className="text-micro text-muted">{V.method} · 10y explicit + terminal</p>
          </div>
          <div className="flex overflow-hidden rounded-control border border-hairline" role="group" aria-label="Scenario">
            {SCENARIOS.map((sc, i) => (
              <button
                key={sc.id}
                type="button"
                aria-pressed={i === scen}
                onClick={() => setScen(i)}
                className={`px-2 py-0.5 text-micro font-medium outline-none transition-colors duration-200 focus-visible:ring-2 focus-visible:ring-brand/40 ${
                  i === scen ? "bg-brand/12 text-brand" : "text-muted hover:bg-surface-3/60 hover:text-foreground"
                }`}
              >
                {sc.label}
              </button>
            ))}
          </div>
        </div>

        <div className="mt-2 flex items-baseline gap-4">
          <div>
            <p className="text-micro uppercase tracking-wide text-muted">Fair value</p>
            <p className="font-mono text-mk-feature font-semibold tabular-nums text-foreground">
              <Odometer value={s.fairValue} play={played} />
            </p>
          </div>
          <div className="transition-opacity delay-[900ms] duration-300 ease-out [[data-mock=armed]_&]:opacity-0">
            <p className="text-micro uppercase tracking-wide text-muted">vs spot {V.spotDisplay}</p>
            <p
              className={`flex items-center gap-0.5 font-mono text-mk-lead font-semibold tabular-nums ${
                s.upsidePositive ? "text-positive" : "text-negative"
              }`}
            >
              {s.upsidePositive ? (
                <ArrowUpRight className="h-4 w-4" strokeWidth={2} />
              ) : (
                <ArrowDownRight className="h-4 w-4" strokeWidth={2} />
              )}
              {s.upside}
            </p>
          </div>
        </div>
        <p className="mt-1 font-mono text-micro tabular-nums text-muted transition-opacity delay-[1000ms] duration-300 sm:truncate [[data-mock=armed]_&]:opacity-0">
          {s.delta == null && V.pricedInGrowth != null && V.deliveredGrowth != null
            ? `${V.pricedInGrowth.label} ${V.pricedInGrowth.display} vs delivered ${V.deliveredGrowth.display}, conditional on WACC and terminal growth`
            : `${s.label} vs base: ${s.delta}`}
        </p>

        {/* Free cash flow chart: labelled units, actuals split from forecast. */}
        <div className="mt-2.5 flex min-h-0 flex-1 flex-col">
          <div className="flex items-center justify-between">
            <span className="text-micro text-muted">Free cash flow, {V.unit}</span>
            <span className="flex items-center gap-2.5 text-micro text-muted">
              <span className="flex items-center gap-1">
                <span aria-hidden="true" className="h-1.5 w-1.5 rounded-xs bg-brand/80" />
                Actuals
              </span>
              <span className="flex items-center gap-1">
                <span aria-hidden="true" className="h-1.5 w-1.5 rounded-xs bg-border-strong" />
                Forecast
              </span>
            </span>
          </div>
          <div className="mt-1 flex h-28 min-h-0 gap-1.5 sm:h-auto sm:flex-1">
            {/* Y axis in billions of the reporting currency. */}
            <div className="flex flex-col justify-between text-right font-mono text-micro tabular-nums text-muted">
              <span>{NICE_MAX / 1e9}</span>
              <span>{NICE_MAX / 2e9}</span>
              <span>0</span>
            </div>
            <div className="relative flex flex-1 items-end gap-1.5">
              {/* Gridlines at 0 / half / max. */}
              <div aria-hidden="true" className="pointer-events-none absolute inset-0">
                <span className="absolute inset-x-0 top-0 border-t border-hairline" />
                <span className="absolute inset-x-0 top-1/2 border-t border-hairline" />
                <span className="absolute inset-x-0 bottom-0 border-t border-border-strong/60" />
              </div>
              {bars.map((b, i) => (
                <div
                  key={b.year}
                  className={`flex h-full flex-1 items-end ${
                    b.kind === "forecast" && i > 0 && bars[i - 1].kind === "actual"
                      ? "border-l border-dashed border-border-strong/70"
                      : ""
                  }`}
                >
                  <div
                    style={{
                      height: `${(b.value / NICE_MAX) * 100}%`,
                      transitionDelay:
                        phase === "play"
                          ? `${b.kind === "actual" ? i * 60 : 200 + i * 60}ms`
                          : `${i * 30}ms`,
                    }}
                    className={`w-full origin-bottom rounded-t-xs transition-[height,transform] duration-500 ease-[cubic-bezier(0.34,1.2,0.64,1)] [[data-mock=armed]_&]:scale-y-0 ${
                      b.kind === "actual" ? "bg-brand/80" : "bg-border-strong"
                    }`}
                  />
                </div>
              ))}
            </div>
          </div>
          <div className="mt-1 flex gap-1.5 pl-6">
            {bars.map((b, i) => (
              <span
                key={b.year}
                className={`flex-1 text-center font-mono text-micro tabular-nums text-muted ${
                  i % 2 === 0 ? "invisible sm:visible" : ""
                }`}
              >
                {b.year}
              </span>
            ))}
          </div>
        </div>

        {/* The derivation: cash flows to per-share value, engine arithmetic. */}
        <p className="mt-2 border-t border-hairline pt-1.5 font-mono text-micro tabular-nums text-muted">
          PV 10y {s.bridge.pvExplicit} + terminal {s.bridge.pvTerminal} − net debt {s.bridge.netDebt} ={" "}
          <span className="text-foreground">{s.bridge.equityValue}</span> ÷ {s.bridge.shares} sh ={" "}
          <span className="text-foreground">{s.bridge.perShare}</span>
        </p>
      </div>
    </div>
  );
}
