/**
 * AI Market Summary — narrates the Scanner's Market Regime + Sector Rotation
 * output into a short investor-facing brief. Pure composition: consumes
 * MarketRegime/MacroSignal (already computed by lib/scanner/index.ts's
 * assessMarketRegime()) and SectorRotationSnapshot (already computed by
 * lib/sector-rotation.ts) — introduces no new scoring/classification logic,
 * only a narrative synthesis call via lib/ai.ts's runPrompt(), matching the
 * "engines decide, AI narrates" split used in lib/movement-explainer.ts.
 */
import { runPrompt } from "./ai";
import { getScannerCache, putScannerCache } from "./db";
import type { MarketRegime, MacroSignal, SectorRotationSnapshot } from "./types";

/** Exported for unit testing — pure, no I/O. */
export function buildMarketSummaryPrompt(
  regime: MarketRegime,
  macroSignals: MacroSignal[],
  sectorRotation: SectorRotationSnapshot | null,
): string {
  const macroDesc = macroSignals
    .filter((s) => s.price != null)
    .map((s) => `${s.name}: ${s.trend}${s.changePercent != null ? ` (${s.changePercent >= 0 ? "+" : ""}${s.changePercent.toFixed(2)}%)` : ""}`)
    .join("; ") || "No macro signal data available.";

  const rotationDesc = sectorRotation
    ? `Sector leaders: ${sectorRotation.leaders.join(", ") || "none"}. Sector laggards: ${sectorRotation.laggards.join(", ") || "none"}.` +
      (sectorRotation.leadershipChanges.length > 0
        ? ` Recent leadership changes: ${sectorRotation.leadershipChanges.map((c) => `${c.sector} #${c.fromRank}→#${c.toRank}`).join(", ")}.`
        : "")
    : "No sector rotation snapshot available.";

  return `You are a macro strategist writing a brief for a portfolio manager.

The PM's dashboard already displays every number below (regime, breadth, each macro tile,
sector ranks). Your job is the connective tissue the dashboard cannot show — what these
readings mean TOGETHER — not a recap.

Three separate measurements (do not conflate them):
- MARKET REGIME: ${regime.trend}${regime.breadthPct != null ? ` (${regime.breadthPct}% of sectors advancing)` : ""}. Sectors advancing most TODAY: ${regime.dominantSectors.join(", ") || "none"}. News-flow themes this scan: ${regime.dominantThemes.join(", ") || "none identified"}.
- MACRO SIGNALS (today): ${macroDesc}
- 1-MONTH PRICE LEADERSHIP: ${rotationDesc}

Write 2-4 sentences, using only the facts above (never invent data), that:
1. Lead with the most decision-relevant tension or confirmation in the data — e.g. today's movers
   diverging from 1-month leaders, breadth disagreeing with the regime label, a leadership change,
   or a macro signal that cuts against equity positioning. If everything is aligned, say so plainly.
2. Do NOT restate figures verbatim (no "X% of sectors advancing", no repeating tile percentages);
   reference readings only to interpret them.
3. If causality is uncertain, say "consistent with" or "suggests" — never assert a cause the data
   cannot support.
4. End with ONE concrete, falsifiable thing to watch that follows from the data (e.g. "whether
   [sector] holds its rank improvement", not generic advice like "stay diversified").

Return ONLY the summary text — no headings, no bullet points, no JSON, no preamble.`;
}

// v2: prompt rewritten to interpret rather than recap — versioned so cached
// summaries generated by the old recap prompt don't outlive it.
const CACHE_KEY_PREFIX = "market-summary-v2";

export async function generateMarketSummary(
  regime: MarketRegime,
  macroSignals: MacroSignal[],
  sectorRotation: SectorRotationSnapshot | null,
): Promise<string> {
  const cacheKey = `${CACHE_KEY_PREFIX}:${regime.trend}:${regime.dominantSectors.join(",")}:${sectorRotation?.asOf ?? "none"}`;
  const cached = getScannerCache(cacheKey);
  if (cached) return cached;

  let summary: string;
  try {
    const raw = await runPrompt("market-summary", buildMarketSummaryPrompt(regime, macroSignals, sectorRotation), {
      maxTokens: 300,
    });
    summary = raw.trim();
  } catch {
    // Deterministic fallback already computed by assessMarketRegime() — never fails.
    summary = regime.summary;
  }

  if (summary) putScannerCache(cacheKey, summary);
  return summary;
}
