import type { ReactNode } from "react";

/**
 * PanelFrame: the product-surface shell around every Capabilities panel.
 * Replaces the old MockupFrame (traffic-light title bar + ILLUSTRATIVE
 * watermark). Panels rendered inside this frame show REAL product output,
 * generated by scripts/landing-panel-data.ts from the shipped engines, so
 * the frame states provenance instead of admitting fabrication: a quiet
 * mono footer carries the ticker/module, the source, and the as-of date.
 *
 * 14px radius, hairline border with a slightly brighter TOP edge (single
 * overhead light source), soft ambient shadow beneath (--depth-1), an
 * app-background body at fixed 16:10, and a 22px provenance footer.
 *
 * Interactive content is allowed (scenario tabs, model switches), so the
 * frame is a labelled group rather than role="img" with a hidden body.
 */
export function PanelFrame({
  children,
  label,
  provenance,
  className = "",
}: {
  children: ReactNode;
  /** Accessible description of the panel. */
  label: string;
  /** Real source line, e.g. "V · Visa Inc. · engine output · as of 2026-08-10". */
  provenance: string;
  className?: string;
}) {
  return (
    <div role="group" aria-label={label} className={`relative ${className}`}>
      {/* Soft ambient glow beneath the frame. */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-x-8 -bottom-6 h-16 rounded-full bg-brand/15 blur-2xl"
      />
      <div className="relative overflow-hidden rounded-[14px] border border-foreground/10 border-t-foreground/20 bg-surface [box-shadow:var(--depth-1)]">
        {/* Fixed 16:10 from sm up. Below sm the body grows to fit: panels
            collapse to stacked layouts instead of shrinking type below
            legibility or hiding content behind a horizontal scroll. */}
        <div data-frame-body className="relative overflow-hidden bg-background sm:aspect-[16/10]">
          <div className="h-full w-full">{children}</div>
        </div>
        <div
          data-provenance
          className="flex h-[22px] items-center justify-between gap-3 border-t border-hairline bg-surface-2 px-3"
        >
          <span className="truncate font-mono text-micro tabular-nums text-muted">{provenance}</span>
        </div>
      </div>
    </div>
  );
}
