/**
 * Equities. The reference implementation of an asset class definition, and the
 * one class whose data path is unchanged by this redesign: its metrics map
 * 1:1 onto the existing StockMetrics (lib/types.ts) produced by the existing
 * lib/dataset.ts + lib/composite.ts pipeline, which is left exactly as it was.
 * The registry describes that pipeline's output; it does not replace it.
 */

import type { AssetClassDefinition, MetricDef } from "./types";
import { SCREENER_SECTORS } from "../yahoo-screener";

const metrics: MetricDef[] = [
  // Size
  {
    key: "marketCap",
    label: "Market Cap",
    description: "Total equity value. Entered in billions.",
    group: "Size & Sector",
    unit: "$B",
    availability: "live",
    source: "yahoo",
    better: null,
    scale: 1e9,
  },
  {
    key: "sector",
    label: "Sector",
    description: "Yahoo's 11-sector taxonomy.",
    group: "Size & Sector",
    unit: "",
    availability: "live",
    source: "yahoo",
    better: null,
    options: SCREENER_SECTORS,
  },

  // Valuation
  {
    key: "forwardPE",
    label: "Forward P/E",
    description: "Price relative to next year's expected earnings.",
    group: "Valuation",
    unit: "x",
    availability: "live",
    source: "yahoo",
    better: "lower",
    step: 0.5,
  },
  {
    key: "pegRatio",
    label: "PEG Ratio",
    description: "Forward P/E divided by EPS growth. Below 1x is the classic 'growth at a reasonable price' line.",
    group: "Valuation",
    unit: "x",
    availability: "derived",
    source: "yahoo",
    formula: "forwardPE / epsGrowthYoY (only when both are positive — a PEG built on negative growth is meaningless)",
    better: "lower",
    step: 0.1,
  },
  {
    key: "evToEbitda",
    label: "EV / EBITDA",
    description: "Enterprise value to operating profit — capital-structure neutral.",
    group: "Valuation",
    unit: "x",
    availability: "live",
    source: "yahoo",
    better: "lower",
    step: 0.5,
  },
  {
    key: "fcfYield",
    label: "FCF Yield",
    description: "Free cash flow as a percentage of market cap.",
    group: "Valuation",
    unit: "%",
    availability: "derived",
    source: "yahoo",
    formula: "freeCashflow / marketCap × 100, discarding |values| > 40% as FX mismatches",
    better: "higher",
    step: 0.5,
  },

  // Growth
  {
    key: "revenueGrowthYoY",
    label: "Revenue Growth YoY",
    description: "Latest annual revenue growth.",
    group: "Growth",
    unit: "%",
    availability: "live",
    source: "yahoo",
    better: "higher",
  },
  {
    key: "revenueCagr3y",
    label: "Revenue CAGR 3Y",
    description: "Three-year compound revenue growth.",
    group: "Growth",
    unit: "%",
    availability: "live",
    source: "yahoo",
    better: "higher",
  },
  {
    key: "epsGrowthYoY",
    label: "EPS Growth YoY",
    description: "Latest annual earnings-per-share growth.",
    group: "Growth",
    unit: "%",
    availability: "live",
    source: "yahoo",
    better: "higher",
  },
  {
    key: "epsCagr3y",
    label: "EPS CAGR 3Y",
    description: "Three-year compound EPS growth.",
    group: "Growth",
    unit: "%",
    availability: "live",
    source: "yahoo",
    better: "higher",
  },

  // Quality
  {
    key: "roic",
    label: "ROIC",
    description: "Return on invested capital — the cleanest read on whether the business creates value.",
    group: "Quality",
    unit: "%",
    availability: "live",
    source: "yahoo",
    better: "higher",
  },
  {
    key: "roe",
    label: "ROE",
    description: "Return on equity.",
    group: "Quality",
    unit: "%",
    availability: "live",
    source: "yahoo",
    better: "higher",
  },
  {
    key: "grossMargin",
    label: "Gross Margin",
    description: "Pricing power and unit economics.",
    group: "Quality",
    unit: "%",
    availability: "live",
    source: "yahoo",
    better: "higher",
  },
  {
    key: "operatingMargin",
    label: "Operating Margin",
    description: "Profitability after operating costs.",
    group: "Quality",
    unit: "%",
    availability: "live",
    source: "yahoo",
    better: "higher",
  },

  // Financial strength
  {
    key: "debtToEquity",
    label: "Debt / Equity",
    description: "Balance-sheet leverage.",
    group: "Financial Strength",
    unit: "x",
    availability: "live",
    source: "yahoo",
    better: "lower",
    step: 0.1,
  },
  {
    key: "netDebtToEbitda",
    label: "Net Debt / EBITDA",
    description: "Years of operating profit needed to clear net debt.",
    group: "Financial Strength",
    unit: "x",
    availability: "derived",
    source: "yahoo",
    formula: "netDebt / ebitda, preferring the annual balance-sheet netDebt time series and falling back to totalDebt − totalCash",
    better: "lower",
    step: 0.1,
  },
  {
    key: "currentRatio",
    label: "Current Ratio",
    description: "Short-term liquidity.",
    group: "Financial Strength",
    unit: "x",
    availability: "live",
    source: "yahoo",
    better: "higher",
    step: 0.1,
  },

  // Cash flow
  {
    key: "fcfMargin",
    label: "FCF Margin",
    description: "Free cash flow as a share of revenue.",
    group: "Cash Flow",
    unit: "%",
    availability: "live",
    source: "yahoo",
    better: "higher",
  },
  {
    key: "fcfGrowthYoY",
    label: "FCF Growth YoY",
    description: "Growth in free cash flow.",
    group: "Cash Flow",
    unit: "%",
    availability: "live",
    source: "yahoo",
    better: "higher",
  },

  // Shareholder returns
  {
    key: "dividendYield",
    label: "Dividend Yield",
    description: "Annual dividend as a percentage of price.",
    group: "Shareholder Returns",
    unit: "%",
    availability: "live",
    source: "yahoo",
    better: "higher",
    step: 0.1,
  },
  {
    key: "buybackYield",
    label: "Buyback Yield",
    description: "Net share count reduction. Negative means dilution.",
    group: "Shareholder Returns",
    unit: "%",
    availability: "live",
    source: "yahoo",
    better: "higher",
    step: 0.1,
  },

  // Momentum
  {
    key: "oneYearReturn",
    label: "1-Year Return",
    description: "Trailing 12-month price return.",
    group: "Momentum",
    unit: "%",
    availability: "live",
    source: "yahoo",
    better: "higher",
  },
  {
    key: "distanceFrom52WkHigh",
    label: "Distance from 52W High",
    description: "How far below the 52-week high the price sits (negative).",
    group: "Momentum",
    unit: "%",
    availability: "live",
    source: "yahoo",
    better: "higher",
  },

  // Market factors
  {
    key: "institutionalOwnership",
    label: "Institutional Ownership",
    description: "Share held by institutions.",
    group: "Market Factors",
    unit: "%",
    availability: "live",
    source: "yahoo",
    better: null,
  },
  {
    key: "earningsSurprisePct",
    label: "Earnings Surprise",
    description: "Latest reported EPS vs consensus.",
    group: "Market Factors",
    unit: "%",
    availability: "live",
    source: "yahoo",
    better: "higher",
  },

  // Composite scores (lib/composite.ts)
  {
    key: "overallScore",
    label: "Overall Score",
    description: "Composite of value, growth, quality and financial health.",
    group: "Composite Scores",
    unit: "score",
    availability: "derived",
    source: "platform",
    formula: "lib/composite.ts — weighted blend of the four factor scores",
    better: "higher",
  },
  {
    key: "valueScore",
    label: "Value Score",
    description: "0-100 valuation attractiveness.",
    group: "Composite Scores",
    unit: "score",
    availability: "derived",
    source: "platform",
    formula: "lib/composite.ts",
    better: "higher",
  },
  {
    key: "growthScore",
    label: "Growth Score",
    description: "0-100 growth strength.",
    group: "Composite Scores",
    unit: "score",
    availability: "derived",
    source: "platform",
    formula: "lib/composite.ts",
    better: "higher",
  },
  {
    key: "qualityScore",
    label: "Quality Score",
    description: "0-100 returns-on-capital and margin quality.",
    group: "Composite Scores",
    unit: "score",
    availability: "derived",
    source: "platform",
    formula: "lib/composite.ts",
    better: "higher",
  },
  {
    key: "financialHealthScore",
    label: "Financial Health Score",
    description: "0-100 balance-sheet resilience.",
    group: "Composite Scores",
    unit: "score",
    availability: "derived",
    source: "platform",
    formula: "lib/composite.ts",
    better: "higher",
  },

  // Declared-but-unscreenable.
  {
    key: "insiderBuying",
    label: "Insider Buying",
    description: "Net insider purchases over the last 6 months.",
    group: "Market Factors",
    unit: "$",
    availability: "unavailable",
    source: null,
    requires:
      "One SEC Form 4 fetch per symbol. Fine for a watchlist, but a 1,000-name universe scan would be ~1,000 EDGAR round-trips per screen. The Scanner's insider signal (lib/event-screener.ts) already covers this for a focused symbol list — use it there instead.",
    better: "higher",
  },
];

export const equityClass: AssetClassDefinition = {
  id: "equity",
  label: "Equities",
  noun: "stocks",
  description: "US-listed common stock, ranked on fundamentals.",
  icon: "TrendingUp",
  accent: "sky",
  assetClass: "equity",
  taskType: "company-research",
  markets: ["US"],
  exchanges: ["NASDAQ", "NYSE", "NYSE American"],
  identifiers: ["ticker"],
  providers: ["yahoo", "sec_edgar", "platform"],
  aliases: ["stocks", "shares", "equities", "companies"],
  capabilities: ["screen", "research", "compare", "portfolio", "watchlist", "chart", "news", "fundamentals"],

  metrics,
  filterGroups: [
    "Composite Scores",
    "Size & Sector",
    "Valuation",
    "Growth",
    "Quality",
    "Financial Strength",
    "Cash Flow",
    "Shareholder Returns",
    "Momentum",
    "Market Factors",
  ],

  rank: [
    { metric: "overallScore", weight: 3 },
    { metric: "qualityScore", weight: 1 },
    { metric: "valueScore", weight: 1 },
  ],

  templates: [
    {
      id: "value",
      name: "Value",
      tagline: "Cheap on earnings and cash flow, with a sound balance sheet",
      filters: {
        valueScore: { kind: "range", min: 60, max: null },
        financialHealthScore: { kind: "range", min: 50, max: null },
      },
      rank: [
        { metric: "valueScore", weight: 3 },
        { metric: "fcfYield", weight: 2 },
        { metric: "financialHealthScore", weight: 1 },
      ],
      sort: { key: "rankScore", dir: "desc" },
    },
    {
      id: "growth",
      name: "Growth",
      tagline: "Top and bottom line compounding fast",
      filters: {
        revenueGrowthYoY: { kind: "range", min: 15, max: null },
        epsGrowthYoY: { kind: "range", min: 10, max: null },
      },
      rank: [
        { metric: "growthScore", weight: 3 },
        { metric: "revenueCagr3y", weight: 2 },
        { metric: "epsCagr3y", weight: 1 },
      ],
      sort: { key: "rankScore", dir: "desc" },
    },
    {
      id: "quality",
      name: "Quality",
      tagline: "High returns on capital, fat margins, low leverage",
      filters: {
        roic: { kind: "range", min: 12, max: null },
        grossMargin: { kind: "range", min: 35, max: null },
        netDebtToEbitda: { kind: "range", min: null, max: 3 },
      },
      rank: [
        { metric: "qualityScore", weight: 3 },
        { metric: "roic", weight: 2 },
        { metric: "fcfMargin", weight: 1 },
      ],
      sort: { key: "rankScore", dir: "desc" },
    },
    {
      id: "dividend",
      name: "Dividend",
      tagline: "Durable income backed by cash flow, not leverage",
      filters: {
        dividendYield: { kind: "range", min: 2.5, max: null },
        financialHealthScore: { kind: "range", min: 55, max: null },
        fcfMargin: { kind: "range", min: 5, max: null },
      },
      rank: [
        { metric: "dividendYield", weight: 3 },
        { metric: "financialHealthScore", weight: 2 },
        { metric: "fcfMargin", weight: 1 },
      ],
      sort: { key: "rankScore", dir: "desc" },
    },
    {
      id: "momentum",
      name: "Momentum",
      tagline: "Strong 1-year trend, still near the highs",
      filters: {
        oneYearReturn: { kind: "range", min: 20, max: null },
        distanceFrom52WkHigh: { kind: "range", min: -15, max: null },
      },
      rank: [
        { metric: "oneYearReturn", weight: 3 },
        { metric: "distanceFrom52WkHigh", weight: 2 },
        { metric: "qualityScore", weight: 1 },
      ],
      sort: { key: "rankScore", dir: "desc" },
    },
    {
      id: "small-cap",
      name: "Small Cap",
      tagline: "Sub-$10B names that still earn their cost of capital",
      filters: {
        marketCap: { kind: "range", min: null, max: 10e9 },
        roic: { kind: "range", min: 8, max: null },
      },
      rank: [
        { metric: "overallScore", weight: 2 },
        { metric: "revenueGrowthYoY", weight: 2 },
        { metric: "roic", weight: 1 },
      ],
      sort: { key: "rankScore", dir: "desc" },
    },
    {
      id: "deep-value",
      name: "Deep Value",
      tagline: "The cheapest decile — and a balance sheet that survives it",
      filters: {
        valueScore: { kind: "range", min: 75, max: null },
        financialHealthScore: { kind: "range", min: 50, max: null },
        forwardPE: { kind: "range", min: null, max: 12 },
      },
      rank: [
        { metric: "valueScore", weight: 4 },
        { metric: "financialHealthScore", weight: 1 },
      ],
      sort: { key: "rankScore", dir: "desc" },
    },
  ],

  columns: [
    { key: "rankScore", label: "Match", align: "right" },
    { key: "overallScore", label: "Overall", align: "right" },
    { key: "valueScore", label: "Value", align: "right" },
    { key: "growthScore", label: "Growth", align: "right" },
    { key: "qualityScore", label: "Quality", align: "right" },
    { key: "marketCap", label: "Mkt Cap", align: "right" },
    { key: "forwardPE", label: "Fwd P/E", align: "right" },
    { key: "revenueGrowthYoY", label: "Rev Gr", align: "right" },
    { key: "roic", label: "ROIC", align: "right" },
    { key: "fcfYield", label: "FCF Yld", align: "right" },
    { key: "dividendYield", label: "Div", align: "right" },
  ],
  defaultSort: { key: "rankScore", dir: "desc" },

  aiPrompt: {
    role: "an equity analyst",
    focus:
      "business quality, valuation versus growth, balance-sheet risk, and whether the screen's top names share a common driver or are a grab-bag",
  },

  chart: { lookbackDays: 365, logScale: false },

  warnings: [
    {
      id: "high-leverage",
      label: "High leverage",
      test: (m) => m.netDebtToEbitda != null && m.netDebtToEbitda > 4,
    },
    {
      id: "shrinking-revenue",
      label: "Revenue shrinking",
      test: (m) => m.revenueGrowthYoY != null && m.revenueGrowthYoY < 0,
    },
    {
      id: "dilution",
      label: "Shareholder dilution",
      test: (m) => m.buybackYield != null && m.buybackYield < -2,
    },
    {
      id: "value-trap",
      label: "Possible value trap — cheap but low quality",
      test: (m) =>
        m.valueScore != null && m.valueScore > 70 && m.qualityScore != null && m.qualityScore < 35,
    },
    {
      id: "negative-fcf",
      label: "Negative free cash flow",
      test: (m) => m.fcfMargin != null && m.fcfMargin < 0,
    },
  ],
};
